---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          ports:
            - name: mongo-database
              containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo-database
spec:
  ports:
    - name: mongo-database
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
